// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtangApp.Api.Data;

#nullable disable

namespace UtangApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtangApp.Api.Entities.Borrower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Borrowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cebu City",
                            BirthDate = new DateOnly(1990, 5, 15),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Email = "juan@email.com",
                            EmergencyContactName = "Maria",
                            EmergencyContactPhone = "09179876543",
                            FirstName = "Juan",
                            LastName = "Dela Cruz",
                            Phone = "09171234567",
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Manila",
                            BirthDate = new DateOnly(1988, 3, 22),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Email = "maria@email.com",
                            EmergencyContactName = "Jose",
                            EmergencyContactPhone = "09189876543",
                            FirstName = "Maria",
                            LastName = "Santos",
                            Phone = "09181234567",
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Davao City",
                            BirthDate = new DateOnly(1995, 11, 8),
                            CreatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            Email = "pedro@email.com",
                            FirstName = "Pedro",
                            LastName = "Reyes",
                            Phone = "09191234567",
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPerTerm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InterestMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("LiquidationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TermCount")
                        .HasColumnType("integer");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPerTerm = 875m,
                            BorrowerId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateOnly(2027, 1, 15),
                            InterestMode = "simple",
                            InterestRate = 5m,
                            LiquidationRate = 0m,
                            Notes = "",
                            PrincipalAmount = 10000m,
                            RemainingBalance = 8750m,
                            StartDate = new DateOnly(2026, 1, 15),
                            Status = "active",
                            TermCount = 12,
                            TermType = "monthly",
                            TotalAmount = 10500m,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AmountPerTerm = 3433.33m,
                            BorrowerId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateOnly(2026, 8, 1),
                            InterestMode = "compound",
                            InterestRate = 3m,
                            LiquidationRate = 0m,
                            Notes = "",
                            PrincipalAmount = 20000m,
                            RemainingBalance = 20600m,
                            StartDate = new DateOnly(2026, 2, 1),
                            Status = "active",
                            TermCount = 6,
                            TermType = "monthly",
                            TotalAmount = 20600m,
                            UpdatedAt = new DateTime(2026, 1, 15, 8, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BorrowerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("OfferDate")
                        .HasColumnType("date");

                    b.Property<decimal>("OfferedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 875m,
                            ContractId = 1,
                            CreatedAt = new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PaymentDate = new DateOnly(2026, 2, 15),
                            ReceiptNumber = "RCP-001"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 875m,
                            ContractId = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "",
                            PaymentDate = new DateOnly(2026, 3, 15),
                            ReceiptNumber = "RCP-002"
                        });
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Contract", b =>
                {
                    b.HasOne("UtangApp.Api.Entities.Borrower", "Borrower")
                        .WithMany("Contracts")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Borrower");
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Offer", b =>
                {
                    b.HasOne("UtangApp.Api.Entities.Borrower", "Borrower")
                        .WithMany("Offers")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Borrower");
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Payment", b =>
                {
                    b.HasOne("UtangApp.Api.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Borrower", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("UtangApp.Api.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
